Upgrade to types-Markdown 3.3.0
I couldn't get `tox -e mypy` to work any more locally:

  mypy: remove tox env folder /home/cjwatson/src/canonical/launchpad/git/launchpad/.tox/mypy
  mypy: install_deps> python -I -m pip install mypy -r requirements/types.txt
  Collecting mypy
    Using cached mypy-1.5.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.0 MB)
  Collecting lxml-stubs==0.4.0 (from -r requirements/types.txt (line 1))
    Using cached lxml_stubs-0.4.0-py3-none-any.whl (13 kB)
  Collecting types-Markdown==0.1.0 (from -r requirements/types.txt (line 2))
    Using cached types_Markdown-0.1.0-py2.py3-none-any.whl (15 kB)
  Collecting types-beautifulsoup4==4.9.0 (from -r requirements/types.txt (line 3))
    Using cached types_beautifulsoup4-4.9.0-py3-none-any.whl (10 kB)
  Collecting types-bleach==3.3.1 (from -r requirements/types.txt (line 4))
    Using cached types_bleach-3.3.1-py2.py3-none-any.whl (4.9 kB)
  Collecting types-oauthlib==3.1.0 (from -r requirements/types.txt (line 5))
    Using cached types_oauthlib-3.1.0-py3-none-any.whl (32 kB)
  Collecting types-psycopg2==2.9.21.4 (from -r requirements/types.txt (line 6))
    Using cached types_psycopg2-2.9.21.4-py3-none-any.whl (17 kB)
  Collecting types-python-dateutil==2.8.1 (from -r requirements/types.txt (line 7))
    Using cached types_python_dateutil-2.8.1-py3-none-any.whl (7.6 kB)
  Collecting types-requests==0.1.13 (from -r requirements/types.txt (line 8))
    Using cached types_requests-0.1.13-py3-none-any.whl (22 kB)
  Collecting types-six==0.1.9 (from -r requirements/types.txt (line 9))
    Using cached types_six-0.1.9-py2.py3-none-any.whl (23 kB)
  Collecting types-urllib3==1.26.25.4 (from -r requirements/types.txt (line 10))
    Using cached types_urllib3-1.26.25.4-py3-none-any.whl (14 kB)
  INFO: pip is looking at multiple versions of types-markdown to determine which version is compatible with other requirements. This could take a while.
  ERROR: Could not find a version that satisfies the requirement types-typing-extensions (from types-markdown) (from versions: 3.7.0, 3.7.1, 3.7.2, 3.7.3)
  ERROR: No matching distribution found for types-typing-extensions

Maybe this is because I haven't rebuilt this virtual environment since I
upgraded to Ubuntu 23.04 and Python 3.11 or something?  In any case,
upgrading `types-Markdown` a bit seems to fix it.