Stop adding Status header in wsgi_application
Adding the Status header here meant that wsgi_application wasn't usable
with zope.testbrowser.wsgi, as webtest.lint complained, for example:

  AssertionError: The Status header cannot be used; it conflicts with
  CGI script, and HTTP status is not given through headers (value: '503
  Service Unavailable').

zope.testbrowser.browser.Browser.headers adds the Status header as of
zope.testbrowser >= 5.0.0, but changing this first makes the upgrade
easier.