lp.scripts.harness: Fix exec() for Python 2
Commit b1e6fe75b6c6ca3f903def0c6bbf4a54d5c4be03 switched
`lp.scripts.harness` from `execfile()` to `exec()`, but there's a
subtlety on Python 2 due to the use of a nested function here.  As a
result, `bin/harness` failed as follows on Python 2:

    Traceback (most recent call last):
      File "bin/harness", line 5, in <module>
        import lp.scripts.harness
      File ".../lib/lp/scripts/harness.py", line 66
        exec(f.read())
    SyntaxError: unqualified exec is not allowed in function '_get_locals' because it contains a nested function with free variables

Explicitly passing `globals()` avoids this.