Fix bugtask-expiration.txt for Python 3
Python 3.5 raises this exception instead:

  TypeError: findExpirableBugTasks() missing 2 required positional
  arguments: 'min_days_old' and 'user'

We don't really care about the fine details.